### ISSUE TITLE
Сломалась авторизация

### ISSUE THREAD

**Issue by Ka3e1** [VKUnicorn/VK-Unicorn#2]
Сломалась авторизация. Пробовал пересоздать базу и создать новое приложение.

`4:10:30 AM] Авторизируемся в ВКонтакте
[4:10:32 AM] Ошибка: не удалось авторизироваться. Причина: Неверный логин или пароль.
[4:10:32 AM] Ошибка: не удалось авторизироваться. Причина:    at VkNet.Utils.Browser.<NextStepAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at VkNet.Utils.Browser.<NextStepAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at VkNet.Utils.Browser.<NextStepAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VkNet.Utils.Browser.<AuthorizeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VkNet.VkApi.BaseAuthorize(IApiAuthParams authParams)
   at VkNet.VkApi.AuthorizeWithAntiCaptcha(IApiAuthParams authParams)
   at VkNet.VkApi.Authorize(IApiAuthParams params)
   at VkNet.VkApi.<>c__DisplayClass46_0.<AuthorizeAsync>b__0()
   at VkNet.Utils.TypeHelper.<>c__DisplayClass2_0.<TryInvokeMethodAsync>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VK_Unicorn.Worker.<AuthorizationTask>d__11.MoveNext()`

**Comment by VKUnicorn** [comment]
Починил
